global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "api"
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
